#!/bin/csh -f
Yphon -Born dielecfij.out -bvec -plot -pdis dfile.scc  <superfij.out -expt exp03.dat
pos2s Symmetry.pos
Yphon -Born dielecfij.out -bvec -plot -pdis dfile.scc  <superfij.out -expt exp03.dat -Gfile symmetry.mode
