#!/bin/csh

unalias rm
unalias cp
unalias mv

set conc = "CONTCAR"
set outc = "OUTCAR"
foreach option ( $* )
  if (x$1 == "x-conc") then
    shift
    set conc = "$1"
    shift
    if ( ! -e $conc ) then
      echo "********CANNOT find file $conc"
      exit(1)
    endif
    continue
  else if (x$1 == "x-outc") then
    shift
    set outc = "$1"
    if ( ! -e $outc ) then
      echo "********CANNOT find file $outc"
      exit(1)
    endif
    shift
    continue
  else if ( "$#argv" != 0 ) then
    shift
  else
    break
  endif
end

foreach trycontcar ( $conc CONTCAR )
  set contcar=$trycontcar
  if ( -e $contcar ) then
    break
  endif
end

if ( ! -e $contcar ) then
  echo Cannot open CONTCAR named $contcar
  exit 1
endif

foreach tryoutcar ( $outc OUTCAR.gz  )
  set outcar=$tryoutcar
  if ( -e $outcar ) then
    break
  endif
end

set gz = `echo $outcar | sed 's/^.*\(.\{3\}\)$/\1/'`
#echo gzzzzzzz $gz
if ( ! -e $outcar ) then
  echo Cannot open OUTCAR named $outcar
  exit 1
else if ( "x$gz" == "x.gz" ) then
  zcat $outcar > t.m.p.OUTCAR
  set outcar = "t.m.p.OUTCAR"
else if ( "$outcar" == "OUTCAR" ) then
else
  zcat $outcar > t.m.p.OUTCAR
  set outcar = "t.m.p.OUTCAR"
endif
wait

set last = `grep ' TOTAL ELASTIC MODULI (kBar)' $outcar -n | tail -1 | awk '{print $1}' | sed 's/://g'`
#echo last $last $outcar
if ( "$last" != "" ) then
  tail +$last $outcar | head -9 | tail +4 | cut -b 6- | awk '{printf "%11.5lf %11.5lf %11.5lf %11.5lf %11.5lf %11.5lf\n",0.1*$1,0.1*$2,0.1*$3,0.1*$4,0.1*$5,0.1*$6}' > Cij.out
endif

if ( -e t.m.p.OUTCAR ) rm t.m.p.OUTCAR
